version: "3.9"

networks:
  auth_network:
    driver: bridge

services:
  auth-service-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: auth-service-test
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth_network

  db:
    image: postgres:17-alpine
    container_name: auth-db-test
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - auth_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
