# File: .github/workflows/ci.yml
name: CI: Lint, Typecheck & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI: Lint, Typecheck & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:7-alpine
        ports:
          - 6380:6379
        options: >-
          --health-cmd="redis-cli -a testredis ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Install dependencies
      run: uv sync --dev

    - name: Lint code
      run: uv run pylint app

    - name: Type checking
      run: uv run mypy app

    - name: Run tests
      env:
        DB_URI: postgresql+asyncpg://testuser:testpass@localhost:5433/testdb
        REDIS_URL: redis://:testredis@localhost:6380/1
        JWT_SECRET_KEY: test_super_secret_jwt_key
      run: uv run pytest -v app/tests
