# File: .github/workflows/lint.yml
name: Lint (auth-service)

on:
  push:
    branches: [main]
    paths:
      - "auth-service/**"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "auth-service/**"
      - ".github/workflows/lint.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth-service
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Cache uv & venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: uv-${{ runner.os }}-${{ hashFiles('auth-service/pyproject.toml', 'auth-service/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Sync dependencies
        run: uv sync --dev

      - name: Run pylint
        run: uv run pylint app
