name: auth-service • Typecheck (mypy via Makefile)

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth-service
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install deps (dev)
        run: uv sync --group dev --extra dev

      - name: Typecheck
        run: make typecheck
